version: "3.7"
services:
  php:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./services/php
    image: php_image_${PROJECT_NAME}
    container_name: php_${PROJECT_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_enable=1 remote_autostart=off remote_port=${XDEBUG_STORM_PORT}
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      - main_network
    depends_on:
      - db
  db:
    image: mysql:8
    restart: unless-stopped
    container_name: db_${PROJECT_NAME}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_LOCAL_PORT}:3306
    volumes:
      - ./services/database/dump:/var/lib/mysql
    networks:
      - main_network
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx_${PROJECT_NAME}
    restart: unless-stopped
    ports:
      - ${NGINX_LOCAL_PORT}:80
    volumes:
      - ../:/var/www
      - ./services/nginx:/etc/nginx/conf.d
    networks:
      - main_network
    depends_on:
      - php
  rabbitmq:
    image: library/rabbitmq:3.8.9
    container_name: rabbit_${PROJECT_NAME}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - ./services/rabbit/data:/var/lib/rabbitmq/
    networks:
      - main_network
networks:
  main_network:
    driver: bridge
    name: ${NETWORK_MAIN}
    ipam:
      driver: default
#      config:
#        - subnet: ${XDEBUG_SUBNET_IP}/${XDEBUG_SUBNET_MASK}
